### ISSUE TITLE
Bump requests/six versions

### ISSUE THREAD

**Issue by rogeriolino** [gerencianet/gn-api-sdk-python#6]
Please bump requests/six versions. These versions are 5 years old and break several lib installs that require some newest version.

I suggest to change `requeriments.txt` constraints to:

    requests>=2.9.1,<3.0.0
    six>=1.9.0,<2.0.0

Regards

**Comment by juracy** [comment]
Newer pip versions starting to report this problem about these requirements!

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

gerencianet 1.1.0 requires requests==2.9.1, but you'll have requests 2.24.0 which is incompatible.
gerencianet 1.1.0 requires six==1.9.0, but you'll have six 1.15.0 which is incompatible.

```

**Comment by guilhermecotaGn** [comment]
Olá, pessoal.
Atendemos à atualização da dependência e acrescentamos os endpoints para utilização do métodos de pagamento Pix!
Confiram na versão 2.0.0
