### ISSUE TITLE
Testando o QRCode

### ISSUE THREAD

**Issue by alexhenriquepv** [gerencianet/gn-api-sdk-python#9]
A API (**sandbox**) devolveu o seguinte QRCode:

`{"qrcode":"00020101021226900014BR.GOV.BCB.PIX2568qrcodes-pix-h.gerencianet.com.br/v2/1945cd30c786425ab6121bba9f49d4405204000053039865802BR5914GERENCIANET SA6010OURO PRETO62070503***6304E615","imagemQrcode": "data:image/png;base64,...etc" }`

Embora eu consiga renderizar esse base64, o link não funciona. Tem alguma forma de testar?

**Comment by guilhermecotaGn** [comment]
Olá, @alexhenriquepv. Como vai?

Você pode [testar se está correta a montagem do EMV/Pix Copia e cola neste site](https://pix.nascent.com.br/tools/pix-qr-decoder/).
Este retorno que obteve, significa que a cobrança Pix foi criada com sucesso. No entanto, até o momento não possível testar um pagamento de uma cobrança gerada em sandbox.

Para testar o pagamento, sugerimos gerar uma cobrança em produção. As transações originadas pela API Pix serão gratuitas até o dia 31/07/2021.
